language: node_js
node_js:
  - "16"
os: linux
dist: xenial

before_script:
  - npm install -g typescript

script:
#  - npm init --yes # Create package.json
#  - tsc --init # Create tsconfig.json
# - ls -l
# Compile
- tsc
# Show main.js content
- cat main.js

deploy:
  edge: true
  provider: releases
  token: $GITHUB_TOKEN
  file: $TRAVIS_BUILD_DIR/main.js
  name: dev-build-$TRAVIS_TAG
  release_notes: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    tags: true

after_deploy:
  - rm -rf $TRAVIS_BUILD_DIR/main.js
